In [2]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
import os

output_dir = os.path.join(os.getcwd(), "data")
os.makedirs(output_dir, exist_ok=True)
output_path = os.path.join(output_dir, "simulated_sales_data.csv")

regions = ['North', 'South', 'East', 'West']
skus = ['SKU_A', 'SKU_B', 'SKU_C']
start_date = datetime(2023, 1, 1)
end_date = datetime(2024, 1, 1)
days = (end_date - start_date).days

data = []

for i in range(days):
    current_date = start_date + timedelta(days=i)
    for region in regions:
        for sku in skus:
            weather = random.choice(['sunny', 'rainy', 'cold', 'hot'])
            event = random.choice(['concert', 'sports', 'none'])
            buzz_score = np.random.randint(0, 100)
            base_sales = np.random.randint(20, 80)

            # Adjust sales with season/weather/event
            if weather == 'cold' and sku == 'SKU_B':
                base_sales += 20
            if event != 'none':
                base_sales += 15
            if buzz_score > 60:
                base_sales += 10

            data.append([
                current_date.strftime('%Y-%m-%d'), sku, region,
                base_sales, weather, event, buzz_score
            ])

# Create DataFrame
df = pd.DataFrame(data, columns=[
    'date', 'sku', 'region', 'units_sold', 'weather', 'event', 'buzz_score'
])

df.to_csv(output_path, index=False)

# Preview first 5 rows
df.head()

         date    sku region  units_sold weather    event  buzz_score
0  2023-01-01  SKU_A  North          62   sunny  concert          75
1  2023-01-01  SKU_B  North          45   sunny  concert           6
2  2023-01-01  SKU_C  North          93    cold  concert          13
3  2023-01-01  SKU_A  South          84     hot   sports          92
4  2023-01-01  SKU_B  South          61    cold     none          69